// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-bFt70qL0nAr6rCyRnb8IG9VqLKYz5Y',
    appId: '1:170774106521:web:d7d4f9e431314284b60308',
    messagingSenderId: '170774106521',
    projectId: 'moodiary-89b7b',
    authDomain: 'moodiary-89b7b.firebaseapp.com',
    storageBucket: 'moodiary-89b7b.firebasestorage.app',
    measurementId: 'G-CTHM8K3CMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9W10RzrU67eHmrZp7hC04zCCESq6WDqA',
    appId: '1:170774106521:android:6f42d46a1bb6cc3db60308',
    messagingSenderId: '170774106521',
    projectId: 'moodiary-89b7b',
    storageBucket: 'moodiary-89b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC25nIn_ldq2wi944uAktbtNadhKFnLZ58',
    appId: '1:170774106521:ios:efdb4ac72313cda7b60308',
    messagingSenderId: '170774106521',
    projectId: 'moodiary-89b7b',
    storageBucket: 'moodiary-89b7b.firebasestorage.app',
    iosBundleId: 'com.example.moodiary',
  );
}
